"""Generate src/brandIcons.ts with the two 24x24 brand paths."""
import re, sys, urllib.request
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

WOFF = sys.argv[1]
OUT = sys.argv[2]
GLYPH = 850; XB = 50; top = GLYPH - 20; s = GLYPH / 24.0
inv = (1 / s, 0, 0, -1 / s, -XB / s, top / s)

font = TTFont(WOFF); gs = font.getGlyphSet()
spen = SVGPathPen(gs); gs['openai'].draw(TransformPen(spen, inv))
openai = re.sub(r'-?\d+\.?\d*',
                lambda m: f'{float(m.group()):.3f}'.rstrip('0').rstrip('.'),
                spen.getCommands())

svg = urllib.request.urlopen(
    'https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/claude.svg',
    timeout=20).read().decode('utf-8')
claude = re.search(r'<path d="([^"]+)"', svg).group(1)

ts = f'''// AUTO-GENERATED by tools/gen_brandicons (do not edit by hand).
// 24x24, y-down SVG path data for the OpenAI and Claude brand marks, used to
// render theme-coloured inline <img> icons in the hover tooltip independently
// of the shared status-bar icon font. Sources: simple-icons (CC0); brand marks
// remain property of their owners.

export const OPENAI_SVG_PATH =
    '{openai}';

export const CLAUDE_SVG_PATH =
    '{claude}';

/**
 * A theme-coloured brand mark as an inline data-URI <img>, sized independently
 * of the status-bar icon font. `color` should track the active theme's editor
 * foreground so the mark stays legible in light and dark themes.
 */
export function brandIconImg(path: string, color: string, size: number): string {{
    const svg =
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${{size}}" height="${{size}}">` +
        `<path fill="${{color}}" d="${{path}}"/></svg>`;
    const uri = 'data:image/svg+xml;base64,' + Buffer.from(svg, 'utf8').toString('base64');
    return `<img src="${{uri}}" width="${{size}}" height="${{size}}" alt="">`;
}}
'''
open(OUT, 'w', encoding='utf-8', newline='\n').write(ts)
print('wrote', OUT, 'openai', len(openai), 'claude', len(claude))
